secrets:
  deps_agentic_ai_migrator:
    secretName: deps-agentic-ai-migrator
  agentic_ai_database:
    secretName: agentic-ai-database
  database_ssl_secret:
    secretName: database-ssl-secret

helm_logs_job:
  serviceAccountName: gitlab-ci
  image:
    path: "/base/kubernetes-helm"
    pullPolicy: IfNotPresent
    tag: "0.1.1"
  resources: {}

registry: ""

migrator:
  image:
    path: "/deps-dev-x01/deps-agentic-ai-migrator"
    pullPolicy: IfNotPresent
    tag: ""
  imagePullSecrets: artifactory
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  args: ''

migration_settings:
  DATABASE_PORT: '5432'
  DATABASE_DRIVER: asyncpg
  DATABASE_DIALECT: postgresql
  DATABASE_REQUIRE_SECURE_TRANSPORT: false
  DATABASE_SSLKEY_PATH: '/home/dbcerts/tls.key'
  DATABASE_SSLCERT_PATH: '/home/dbcerts/tls.crt'
  DATABASE_SSLROOTCERT_PATH: '/home/dbcerts/root.crt'

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000

helm:
  enabled: false

csi:
  csi_default_name: deps-agentic-ai-migrator
  vault_namespace: 'k8s-dev'
  roleName: 'k8s-dev'
  vaultKubernetesMountPath: 'kubernetes-dev'

secrets_location:
  secrets_default_path: "/mnt/secrets-store"

service_account:
  serviceAccountName: 'deps-develop'

# Enabled vault settings means that secrets are pulled from hashicorp vault server.
vault_settings:
  enabled: false

migrator_vault_enabled:
  env:
    - name: DATABASE_HOST
      valueFrom:
        secretKeyRef:
          name: deps-agentic-ai-migrator
          key: database-host
    - name: DATABASE_USER
      valueFrom:
        secretKeyRef:
          name: deps-agentic-ai-migrator
          key: user
    - name: DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: deps-agentic-ai-migrator
          key: password
    - name: DATABASE_DB
      valueFrom:
        secretKeyRef:
          name: deps-agentic-ai-migrator
          key: database-db

migrator_vault_disabled:
  env:
    - name: DATABASE_HOST
      valueFrom:
        secretKeyRef:
          name: common-secret
          key: database-host
    - name: DATABASE_USER
      valueFrom:
        secretKeyRef:
          name: agentic-ai-database
          key: user
    - name: DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: agentic-ai-database
          key: password
    - name: DATABASE_DB
      valueFrom:
        secretKeyRef:
          name: agentic-ai-database
          key: database-db
